# Generated by Django 2.2.5 on 2021-04-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_bot', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='ID Телеграм чата')),
            ],
            options={
                'verbose_name': 'Телеграм клиент',
                'verbose_name_plural': 'Телеграм клиенты',
            },
        ),
        migrations.CreateModel(
            name='TelegramReplyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код сообщения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_html', models.BooleanField(blank=True, default=False, verbose_name='HTML')),
            ],
            options={
                'verbose_name': 'Шаблон ответа в Телеграм боте',
                'verbose_name_plural': 'Шаблоны ответа в Телеграм боте',
            },
        ),
    ]
