# Generated by Django 2.2.5 on 2020-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastfood',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='consist',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
