# Generated by Django 2.2.5 on 2021-08-30 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201003_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('emoji', models.CharField(max_length=100, verbose_name='Эмоджи')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='fastfood',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='type',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения'),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastfood',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fast_foods', to='main.FoodType'),
            preserve_default=False,
        ),
    ]
