# Generated by Django 2.2.5 on 2021-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210830_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Эмоджи'),
        ),
    ]
